// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymtaqcneuyeawdqxgaqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdGFxY25ldXllYXdkcXhnYXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODAyMjAsImV4cCI6MjA1NjM1NjIyMH0.AMdz11R8Dn3IgKikY0nYNgyWJ0e7PzHU5v15_2J6OVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);